.TH SR-DHCP-REGISTER 1 "JANUARY 2012" "SR Router" "Management Utilities"
.SH NAME 
sr-dhcp-register \- Register a host with a static DHCP address
.SH SYNOPSIS
.B sr-dhcp-register
.I mac
.I subnet-name
.SH DESCRIPTION
Registers
.I mac
with a static address on the specified subnet.  Valid subnets are:
.IP management
IP Range: 172.18.2.2-254
.IP staff
IP Range: 172.18.4.2-254
.IP compnet
IP Range: 172.18.5.2-254
.IP video
IP Range: 172.18.6.2-254
.SH OPTIONS
.IP mac
The MAC address of the host.
.IP subnet-name
The subnet to allocate a new address from.
.SH AUTHOR
Chris Malton <cmalton at studentrobotics dot org>
.SH SEE ALSO
.BR dhcpd.conf (5)
